# Generated by Django 3.2 on 2021-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_neighborhood_profile_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
