# Generated by Django 3.2 on 2021-04-10 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hoods'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
    ]
