# Generated by Django 3.2 on 2021-04-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210410_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Neighborhood',
            new_name='neighborhood',
        ),
    ]
